version: '3.4'
services:
  api:
    #image: car-rental/nestjs-dockerized
    build:
      dockerfile: Dockerfile
      context: .
      target:
        dev
    depends_on:
      - postgres
    environment:
      DATABASE_PORT: 5432
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    container_name: database
    ports:
      - 35000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_rental_db
      POSTGRES_PORT: 5432